# Generated by Django 3.1.8 on 2022-04-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('class_schedule', '0004_auto_20220430_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllScheduleProfessors',
        ),
    ]
