# Generated by Django 3.1.8 on 2022-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_professors_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='faculty_rank',
            field=models.TextField(choices=[('Instructor', 'Instructor'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('University Professor', 'University Professor')], default='Instructor'),
        ),
        migrations.AddField(
            model_name='professors',
            name='salary_grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='professors',
            name='step',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '8'), (7, '8')], default=1),
        ),
        migrations.AddField(
            model_name='professors',
            name='sub_rank',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI')], default=1),
        ),
    ]
